### ISSUE TITLE
关于 ss-panel-v3-mod_UIChanges 对 CloudHammer 运营实体构成侵权的函告

### ISSUE THREAD

**Issue by CloudHammerDev** [NimaQu/ss-panel-v3-mod_UIChanges#27]
至 ss-panel-v3-mod UI Changes 所有开发成员：

我谨代表 CloudHammer 运营实体（中国大陆），做出如下声明。

除非另有说明，CloudHammer 全部运营实体拥有对旗下所有服务的公开展示的元素保留所有权利。
最近我们发现贵团队在开发中在部分代码中涉嫌模仿、抄袭了 CloudHammer 运营实体的用户中心的商店部分的有关代码（CloudHammer 运营实体和开发团队持有该部分代码，且该部分代码在没有违反 ss-panel-v3-mod glzjin mod 的 MIT 开源协议的前提下并没有开源）。

https://github.com/NimaQu/ss-panel-v3-mod_UIChanges/blob/master/resources/views/material/user/shop.tpl

此行为已经严重影响了 CloudHammer 全部运营实体的声誉和正常经营活动，因此我方鉴于上述事实要求贵开发团队立即停止一切侵权行为，包括但不限于：

- 立即撤下涉嫌侵犯 CloudHammer 运营实体的知识产权的代码、文案、图像、音频等内容
- 在未得到 CloudHammer 运营实体的书面允许下，引用 CloudHammer 运营实体的网站、用户中心的文案、界面等可以用于宣传和盈利目的的文字、图像、音频等内容。

我方将保留一切权利用于维护我方自身合法利益。
如有任何相关问题，请贵开发团队在三个工作日（中国大陆）内与我方运营人员联系，协商处理相关事宜。请通过 CloudHammerDev@protonmail.com 联系我方。

特此函告。

> ss-panel-v3-mod UI Changes 所有开发成员中的任何人如有需要，我方均可以提供 PDF 版本附件。

CloudHammer 运营实体（中国大陆）
2018 年 4 月 6 日

**Comment by NimaQu** [comment]
您好
对于贵司反馈的问题，我方已使用 `git push --force` 清除了相关代码，请贵司进行复核，对贵司造成的不良影响，在这里表示歉意，今后我们会加强对代码提交的审核。

ss-panel-v3-mod_UIChanges 开发团队  -NimaQu
2018 年 4 月 6 日
